# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03744d2fe3d07056a4d4720f58482a3788b12a433506d0d40671cab6788c7f3b2c2463371e7b5266dbbe44d0ced7d8dec37f3ed69a80c38165e17c28eef01436

test:
  secret_key_base: 88e1fd9d435bbe85342bfb3638488bb60204f994390817857948d54d4cb0be61e4a6af3ba815cfbea1593f79873631ce91569b0b2a9951247c8faedfa4f3eb2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
